#!/bin/zsh

export PATH=$PATH:/usr/bin:/usr/local/bin

/usr/bin/ssh -i ~/.ssh/gcp -D 1080 -f -N -C -q xusyd1222@35.212.233.223 

path="$HOME/.config/"

repos=(i3 kitty mpd nvim picom polybar rofi Scripts)

for DIR in "${repos[@]}"; do
    $HOME/Custom/Scripts/git_auto "$path/$DIR"
done

echo "All Done"

